id: cc_security_audit
description: ClawControl workflow (editable) for security audits and risk assessment, with optional supporting code review.
stages:
  - ref: security
    agent: security
    canVeto: true

  - ref: build_review
    agent: build_review
    optional: true
    condition: code_review_needed
